# Generated by Django 5.0.6 on 2024-05-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_categoryimage_productdb_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='PRODUCTPRICE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
