# Generated by Django 5.0.6 on 2024-06-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY', models.CharField(blank=True, max_length=100, null=True)),
                ('PRODUCTNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PRODUCTPRICE', models.IntegerField(blank=True, null=True)),
                ('PRODUCTDESCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
                ('PRODUCTIMAGE', models.ImageField(blank=True, null=True, upload_to='productimages')),
            ],
        ),
    ]
